import test from 'node:test';
import assert from 'node:assert/strict';
import { build } from 'esbuild';
const root=new URL('../',import.meta.url);
async function module(name) { const b=await build({entryPoints:[new URL('src/'+name+'.ts',root).pathname],bundle:true,write:false,format:'esm',platform:'node'}); return import('data:text/javascript;base64,'+Buffer.from(b.outputFiles[0].text).toString('base64')); }
const c=await module('comment-core'), i=await module('image-core');
const message=(text='疑问 %% <script> & 中文') => ({id:'msg-1',author:'我',text,created:'2026-10-04T11:00:00Z',updated:'2026-10-04T11:00:00Z'});
function doc(text='这一段有个疑问\n\n另一段正文\n') { return c.addComment(text,3,6,message(),'thread-1'); }
const thread=text => c.parseComments(text).threads[0];
test('comments: unicode, special characters, deterministic roundtrip',() => { const text=doc(), d=c.parseComments(text); assert.equal(d.version,2); assert.equal(d.threads[0].messages[0].text,message().text); assert.equal(c.writeComments(d.body,d.threads),text); assert.equal((text.match(/^%%$/gm)||[]).length,2); });
test('comments: blank text and invalid ids fail before writes',() => { assert.throws(() => c.addComment('正文',0,2,message(' '),'thread-1')); assert.throws(() => c.addComment('正文',0,2,message(),'bad:ID')); });
test('comments: CRLF and BOM frontmatter protected',() => { for (const start of ['','\uFEFF']) { const text=start+'---\r\ntitle: hello\r\n---\r\n正文\r\n'; assert.throws(() => c.addComment(text,8,12,message(),'thread-1')); const p=text.indexOf('正文'); assert.equal(c.parseComments(c.addComment(text,p,p+2,message(),'thread-1')).threads.length,1); } });
for (const [name,body,from,to] of [['heading','# 标题\n\n正文',2,4],['list','- 第一项\n- 第二项',2,5],['quote','> 引用内容\n',2,6],['inline markup','正文 `code` 与 [链接](note.md)',4,8]]) test('comments: structure remains at line start: '+name,() => { const text=c.addComment(body,from,to,message(),'thread-1'); assert.ok(text.startsWith(body.split('\n')[0])); assert.equal(c.locateComment(c.parseComments(text).body,thread(text)).state,'attached'); });
test('comments: insertion and paragraph cut/paste retain anchor',() => { const text=doc(), d=c.parseComments(text), first=d.body.split('\n\n')[0]; for (const body of ['新增前文\n\n'+d.body,'另一段正文\n\n'+first+'\n']) { const a=c.locateComment(body,d.threads[0]); assert.equal(a.state,'attached'); assert.equal(body.slice(a.from,a.to),'有个疑'); } });
test('comments: changed quote falls back to paragraph',() => { const d=c.parseComments(doc()); const a=c.locateComment(d.body.replace('有个疑问','新的内容'),d.threads[0]); assert.equal(a.state,'attached'); assert.equal(a.exact,false); });
test('comments: duplicate block anchors detach',() => { const d=c.parseComments(doc()); assert.equal(c.locateComment(d.body+d.body,d.threads[0]).state,'detached'); });
test('comments: a missing marker recovers only a unique quote',() => { const d=c.parseComments(doc()), body=c.stripCommentMarkers(d.body); assert.equal(c.locateComment(body,d.threads[0]).state,'recovered'); const t={...d.threads[0],anchor:{...d.threads[0].anchor,prefix:'',suffix:''}}; assert.equal(c.locateComment(body+'\n'+body,t).state,'detached'); });
test('comments: multiple threads share a paragraph; final delete removes anchor',() => { let text=doc(); text=c.addComment(text,0,2,{...message(),id:'msg-2'},'thread-2'); const d=c.parseComments(text); assert.equal(d.threads[0].anchor.blockId,d.threads[1].anchor.blockId); text=c.deleteComment(text,'thread-1'); assert.equal(c.locateComment(c.parseComments(text).body,thread(text)).state,'attached'); text=c.deleteComment(text,'thread-2'); assert.ok(!text.includes('fl-block')); assert.ok(!text.includes('feishu-lite-comments')); });
test('comments: reply, editing, resolve and reopening',() => { let text=doc(); text=c.updateThread(text,'thread-1',t => { t.messages.push({...message('回复'),id:'reply-1'}); t.status='resolved'; }); assert.equal(thread(text).messages.length,2); assert.equal(thread(text).status,'resolved'); text=c.updateThread(text,'thread-1',t => { t.status='open'; t.messages[1].text='修改回复'; }); assert.equal(thread(text).messages[1].text,'修改回复'); });
test('comments: reanchor preserves original excerpt',() => { const before=doc(), original=thread(before).excerpt, p=before.indexOf('另一段'); const after=c.reanchorComment(before,'thread-1',p,p+3); assert.equal(thread(after).excerpt,original); assert.equal(thread(after).anchor.quote,'另一段'); assert.equal((after.match(/fl-block:/g)||[]).length,1); });
test('comments: move appends excerpt and retains source prose',() => { const before=doc(), plan=c.planCommentMove(before,'目标正文\n','thread-1'); assert.equal(c.parseComments(plan.source).threads.length,0); assert.equal(c.stripCommentMarkers(c.parseComments(plan.source).body).trim(),c.stripCommentMarkers(c.parseComments(before).body).trim()); assert.equal(thread(plan.target).excerpt,thread(before).excerpt); assert.equal(c.locateComment(c.parseComments(plan.target).body,thread(plan.target)).state,'attached'); });
test('comments: move can associate existing target paragraph',() => { const plan=c.planCommentMove(doc(),'目标已有内容\n','thread-1',{from:2,to:4}); assert.equal(thread(plan.target).anchor.quote,'已有'); assert.ok(!c.parseComments(plan.target).body.includes('> ')); assert.throws(() => c.planCommentMove(doc(),doc(),'thread-1')); });
for (const [name,mutate] of [['unknown version',s => s.replace('v2','v99')],['bad JSON',s => s.replace('"status":','broken:')],['duplicate store',s => s+s],['conflict',s => '<<<<<<< HEAD\n'+s],['truncated',s => s.replace('/feishu-lite-comments','broken')],['duplicate ID',s => s.replace(/^(\{.*\})$/m,'$1\n$1')]]) test('comments: refuse unsafe storage: '+name,() => assert.throws(() => c.parseComments(mutate(doc()))));
test('comments: legacy v1 can be read and reanchored into v2',() => { const t={id:'thread-1',status:'open',created:'now',updated:'now',anchor:{quote:'正文',prefix:'',suffix:''},messages:[message()]}; const text='%%fl-comment:thread-1:start%%正文%%fl-comment:thread-1:end%%\n\n%%\nfeishu-lite-comments:v1\n'+JSON.stringify(t)+'\n/feishu-lite-comments\n%%\n'; const d=c.parseComments(text); assert.equal(d.threads[0].excerpt,'正文'); const from=text.indexOf('正文'); const next=c.reanchorComment(text,'thread-1',from,from+2); assert.equal(c.parseComments(next).version,2); assert.ok(next.startsWith('正文 %%fl-block:')); });
test('comments: fences, tables, hidden records and multi-paragraph selection protected',() => { for (const text of ['```js\n代码\n```','| 标题 |\n| --- |\n| 内容 |','%%\n隐藏内容\n%%','第一段\n\n第二段']) assert.throws(() => c.addComment(text,0,text.length,message(),'thread-1')); });
test('comments: export includes original and replies',() => assert.ok(c.exportComments(doc(),'测试').includes('疑问 %% <script>')));

for (const text of ['![[图床/a.png]]','![[图床/a.png|说明|320x200]]','![截图|480](<图床/a b.png>)','![图](https://example.com/a.png "title")','![图](图床/a(1).png)']) test('images: parse and width/caption roundtrip: '+text,() => { const ref=i.parseImages(text)[0]; assert.ok(ref); let next=i.patchImage(text,ref,{width:640,caption:'图注 %% 中文\n第二行'}); const parsed=i.parseImages(next)[0]; assert.equal(parsed.width,640); assert.equal(parsed.height,undefined); assert.equal(parsed.caption,'图注 %% 中文\n第二行'); next=i.patchImage(next,parsed,{width:0,caption:''}); assert.equal(i.parseImages(next)[0].width,undefined); assert.equal(i.parseImages(next)[0].id,parsed.id); });
test('images: syntax examples inside code/frontmatter/comments are excluded',() => { assert.equal(i.parseImages('---\nimage: ![[a.png]]\n---\n```\n![[a.png]]\n```\n`![[a.png]]`\n%%\n![[a.png]]\n%%\n![[b.png]]').length,1); });
test('images: duplicate paths address a specific occurrence',() => { const text='![[a.png]]\n中间正文\n![[a.png]]\n', refs=i.parseImages(text); const next=i.patchImage(text,refs[1],{caption:'第二张'}); assert.equal(i.parseImages(next)[0].caption,''); assert.equal(i.parseImages(next)[1].caption,'第二张'); });
test('images: ambiguous copied references are refused',() => { const text='![[a.png]]\n', ref=i.parseImages(text)[0], next=i.patchImage(text,ref,{caption:'图注'}), identified=i.parseImages(next)[0]; assert.throws(() => i.patchImage(next+next,identified,{width:10})); });
test('images: changes around non-identified references are refused',() => { const text='![[a.png]]\n', ref=i.parseImages(text)[0]; assert.throws(() => i.patchImage('新增\n'+text,ref,{caption:'x'})); });
test('images: replacement retains alt, width and caption',() => { let text='![[a.png|说明|300]]'; text=i.patchImage(text,i.parseImages(text)[0],{caption:'图注'}); text=i.patchImage(text,i.parseImages(text)[0],{target:'b.png'}); const r=i.parseImages(text)[0]; assert.equal(r.target,'b.png'); assert.equal(r.alt,'说明'); assert.equal(r.width,300); assert.equal(r.caption,'图注'); });
for (const eol of ['\n','\r\n']) test('images: grid layout, columns, reorder and unwrap '+JSON.stringify(eol),() => { let text=['说明','','![[a.png]]','','![[b.png]]','','后续正文'].join(eol); text=i.patchImage(text,i.parseImages(text)[0],{caption:'第一张'}); text=i.setImageGrid(text,i.parseImages(text)[0],2); assert.equal(i.imageGrid(text,i.parseImages(text)[0]).cols,2); text=i.setImageGrid(text,i.parseImages(text)[0],3); text=i.reorderImage(text,i.parseImages(text)[1],-1); assert.deepEqual(i.parseImages(text).map(r => r.target),['b.png','a.png']); assert.equal(i.parseImages(text)[1].caption,'第一张'); text=i.setImageGrid(text,i.parseImages(text)[0],0); assert.ok(!text.includes('[!img-')); assert.ok(text.includes('后续正文')); });
test('images: reordering last row without newline remains valid',() => { const text='> [!img-2]\n> ![[a.png]]\n> ![[b.png]]'; const next=i.reorderImage(text,i.parseImages(text)[1],-1); assert.deepEqual(i.parseImages(next).map(r => r.target),['b.png','a.png']); assert.ok(next.includes('b.png]]\n> ![[a')); });
test('images: mixed-content grid is protected',() => { const text='> [!img-2]\n> ![[a.png]]\n> 正文\n'; assert.throws(() => i.setImageGrid(text,i.parseImages(text)[0],0)); });
test('images: bad metadata and widths fail safely',() => { assert.throws(() => i.parseImages('![[a.png]] %%fl-image:{broken}%%')); for (const n of [-1,NaN,0.5,10001]) assert.throws(() => i.patchImage('![[a.png]]',i.parseImages('![[a.png]]')[0],{width:n})); });
const project=() => ({version:1,original:'图床/a.png',width:800,height:600,crop:{x:10,y:20,width:400,height:300},shapes:[{id:'s-1',kind:'arrow',color:'#ff0000',width:3,points:[{x:20,y:30},{x:300,y:200}]}]});
test('projects: valid portable project and coordinate conversion',() => { assert.equal(i.validateProject(project()).original,'图床/a.png'); assert.deepEqual(i.canvasPoint({x:210,y:170},{x:10,y:20,width:400,height:300},800,600),{x:400,y:300}); });
test('projects: crop is clamped, reversed gestures normalized',() => assert.deepEqual(i.normalizeRect({x:900,y:700},{x:20,y:30},800,600),{x:20,y:30,width:780,height:570}));
for (const [name,change] of [['version',p => p.version=9],['path',p => p.original='../a.png'],['oversized',p => p.width=100000],['crop bounds',p => p.crop.width=1000],['negative point',p => p.shapes[0].points[0].x=-1],['color',p => p.shapes[0].color='url(x)'],['duplicate shapes',p => p.shapes.push(p.shapes[0])]]) test('projects: reject '+name,() => { const p=project(); change(p); assert.throws(() => i.validateProject(p)); });
test('comments: selecting an already annotated paragraph can include its hidden end marker',()=>{const before=doc(),body=c.parseComments(before).body,p=c.commentParagraphs(body)[0];const next=c.addComment(before,p.from,p.to,{...message(),id:'msg-2'},'thread-2');assert.equal(c.parseComments(next).threads.length,2);assert.equal(c.parseComments(next).threads[1].anchor.quote,'这一段有个疑问');});
test('comments: duplicate paragraph anchors can be repaired by reassociation',()=>{const before=doc(),d=c.parseComments(before),first=d.body.split('\n\n')[0];let copied=c.writeComments(first+'\n\n'+first+'\n',d.threads);assert.equal(c.locateComment(c.parseComments(copied).body,thread(copied)).state,'detached');copied=c.reanchorComment(copied,'thread-1',3,6);assert.equal(c.locateComment(c.parseComments(copied).body,thread(copied)).state,'attached');assert.equal((copied.match(/fl-block:/g)||[]).length,1);});
test('projects: negative off-image crop gestures intersect image bounds',()=>assert.deepEqual(i.normalizeRect({x:-30,y:-20},{x:20,y:30},800,600),{x:0,y:0,width:20,height:30}));
test('projects: source URL is not accepted as a vault path',()=>assert.throws(()=>i.validateProject({...project(),original:'https://example.com/a.png'})));

test('comments: heading anchors stay out of native section titles',()=> { const result=c.addComment('# 标题 ###\n\n正文',2,4,message(),'heading-id'); assert.equal(result.split('\n')[0],'# 标题 ###'); assert.match(result.split('\n')[1],/^%%fl-block:/); assert.equal(c.locateComment(c.parseComments(result).body,thread(result)).state,'attached'); });
for(const align of ['left','center','right']) test('images: alignment persists across width, replacement and caption changes: '+align,()=> { let text=i.patchImage('![[a.png]]',i.parseImages('![[a.png]]')[0],{align,width:320}); const id=i.parseImages(text)[0].id; text=i.patchImage(text,i.parseImages(text)[0],{target:'b.png',caption:'说明',width:280}); assert.equal(i.parseImages(text)[0].align,align); assert.equal(i.parseImages(text)[0].id,id); });
test('images: unknown alignment fails closed',()=> { const text=i.patchImage('![[a.png]]',i.parseImages('![[a.png]]')[0],{align:'center'}); assert.throws(()=>i.parseImages(text.replace('center','unsafe'))); assert.throws(()=>i.patchImage(text,i.parseImages(text)[0],{align:'unsafe'})); });
test('images: image/text layout preserves metadata and rich Markdown through side switching and unwrap',()=> { let text='前面的正文\n\n![[a.png]]\n\n后面的正文\n'; text=i.patchImage(text,i.parseImages(text)[0],{width:280,caption:'原图说明',align:'center'}); const id=i.parseImages(text)[0].id; const body='**调用链**\n\n- 第一处\n- 第二处\n\n> 引用\n\n```js\nconsole.log(1)\n```'; text=i.setImageText(text,i.parseImages(text)[0],'left',body); assert.equal(i.imageTextBlock(text,i.parseImages(text)[0]).content,body); text=i.setImageText(text,i.parseImages(text)[0],'right'); assert.equal(i.imageTextBlock(text,i.parseImages(text)[0]).side,'right'); assert.equal(i.imageTextBlock(text,i.parseImages(text)[0]).content,body); text=i.setImageText(text,i.parseImages(text)[0],'none'); assert.ok(text.includes(body)); assert.ok(text.includes('前面的正文')); assert.ok(text.includes('后面的正文')); assert.equal(i.parseImages(text)[0].id,id); assert.equal(i.parseImages(text)[0].align,'center'); assert.equal(i.parseImages(text)[0].caption,'原图说明'); });
test('images: image/text blocks preserve repeated occurrences and CRLF',()=> { let text='![[a.png]]\r\n\r\n中间正文\r\n\r\n![[a.png]]\r\n'; text=i.setImageText(text,i.parseImages(text)[1],'left','一行\n\n第二行'); assert.equal(i.imageTextBlock(text,i.parseImages(text)[0]),null); assert.equal(i.imageTextBlock(text,i.parseImages(text)[1]).content,'一行\n\n第二行'); assert.ok(!/(?<!\r)\n/.test(text)); });
test('images: unsafe mixed layouts fail before mutation',()=> { for(const text of ['正文 ![[a.png]]\n','> [!img-2]\n> ![[a.png]]\n']) assert.throws(()=>i.setImageText(text,i.parseImages(text)[0],'left','说明')); let text=i.setImageText('![[a.png]]\n',i.parseImages('![[a.png]]\n')[0],'left'); for(const body of ['![[b.png]]','%%fl-image:{}%%','[!img-text-left]']) assert.throws(()=>i.setImageText(text,i.parseImages(text)[0],'right',body)); });
test('images: image/text callouts end before adjacent prose and quotes',()=> { const text='![[a.png]]\n> 外部引用\n'; const result=i.setImageText(text,i.parseImages(text)[0],'left','文字'); assert.ok(result.includes('> 文字\n\n> 外部引用')); assert.equal(i.imageTextBlock(result,i.parseImages(result)[0]).content,'文字'); });
test('images: side and corner resize respect aspect ratio, center anchor and bounds',()=> { assert.equal(i.resizedImageWidth(400,200,-80,0,1,0,800),320); assert.equal(i.resizedImageWidth(400,200,-80,-40,1,1,800),320); assert.equal(i.resizedImageWidth(400,200,80,40,-1,-1,800),320); assert.equal(i.resizedImageWidth(400,200,-40,0,1,0,800,true),320); assert.equal(i.resizedImageWidth(400,200,2000,0,1,0,600),600); assert.equal(i.resizedImageWidth(400,200,-2000,0,1,0,800),24); assert.equal(i.resizedImageWidth(400,200,0,0,1,0,12),12); assert.throws(()=>i.resizedImageWidth(0,200,0,0,1,0,800)); });
for(const [dx,dy] of [[100,0],[-100,0],[0,100],[0,-100],[100,100],[-100,100],[100,-100],[-100,-100]])test('arrows: connected filled outline points to drag endpoint '+dx+','+dy,()=>{
 const from={x:200,y:200},to={x:200+dx,y:200+dy},outline=i.arrowOutline(from,to,5),length=Math.hypot(dx,dy);
 assert.equal(outline.length,7);assert.deepEqual(outline[3],to);
 for(const p of outline){assert.ok(Number.isFinite(p.x)&&Number.isFinite(p.y));const along=((p.x-from.x)*dx+(p.y-from.y)*dy)/length;assert.ok(along>=-1e-8&&along<=length+1e-8);}
 const shaft=Math.hypot(outline[0].x-outline[6].x,outline[0].y-outline[6].y),head=Math.hypot(outline[2].x-outline[4].x,outline[2].y-outline[4].y);assert.ok(Math.abs(shaft-5)<1e-8);assert.ok(head>=shaft*3);
});
test('arrows: short or zero-length gestures retain valid proportions',()=>{assert.deepEqual(i.arrowOutline({x:0,y:0},{x:0,y:0},5),[]);const p=i.arrowOutline({x:0,y:0},{x:2,y:0},100);assert.ok(p.every(a=>a.x>=0&&a.x<=2&&Math.abs(a.y)<=.6));assert.ok(p[1].x>0);assert.throws(()=>i.arrowOutline({x:NaN,y:0},{x:2,y:0},5));});
test('arrows: preview width converts to portable source pixels within project budget',()=>{assert.equal(i.arrowStrokeWidth(5,2400,600),20);assert.equal(i.arrowStrokeWidth(5,600,600),5);assert.equal(i.arrowStrokeWidth(5,16384,200),200);assert.throws(()=>i.arrowStrokeWidth(5,2400,0));});
