import test from 'node:test';
import assert from 'node:assert/strict';
import { build } from 'esbuild';
const root=new URL('../',import.meta.url).pathname;
const stub=`export class TFile {constructor(path){this.path=path;this.name=path.split('/').pop();this.extension=this.name.split('.').pop();this.stat={mtime:0};}} export class MarkdownView {constructor(file,editor){this.file=file;this.editor=editor;} getMode(){return 'source';}} export class Notice {}`;
const built=await build({stdin:{contents:'export * from "./src/note-edit"; export {sweepUnusedAttachments} from "./src/attachment-clean"; export {TFile,MarkdownView} from "obsidian";',resolveDir:root},bundle:true,write:false,format:'esm',platform:'node',plugins:[{name:'mock-obsidian',setup(b){b.onResolve({filter:/^obsidian$/},()=>({path:'obsidian',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:stub,loader:'js'}));}}]});
const m=await import('data:text/javascript;base64,'+Buffer.from(built.outputFiles[0].text).toString('base64'));
function appFixture() {
 const files=new Map(), texts=new Map(), journals=new Map(), dirs=new Set(), views=[], trash=[];
 const app={workspace:{getActiveViewOfType:()=>views[0]?.view??null,getLeavesOfType:()=>views},vault:{getFiles:()=>[...files.values()],getAbstractFileByPath:p=>files.get(p),read:async f=>texts.get(f.path),cachedRead:async f=>texts.get(f.path),process:async(f,fn)=>{const value=fn(texts.get(f.path));texts.set(f.path,value);app.afterProcess?.(f);return value;},adapter:{exists:async p=>dirs.has(p)||journals.has(p),mkdir:async p=>dirs.add(p),write:async(p,t)=>journals.set(p,t),read:async p=>journals.get(p),remove:async p=>journals.delete(p),list:async()=>({files:[...journals.keys()],folders:[]})}},metadataCache:{resolvedLinks:{}},fileManager:{trashFile:async f=>trash.push(f.path)}};
 const add=(path,text)=>{const f=new m.TFile(path);files.set(path,f);texts.set(path,text);return f;};
 const editor=(file,value)=>{const e={value,getValue(){return this.value},offsetToPos(n){return {line:0,ch:n}},replaceRange(s,a,b){this.value=this.value.slice(0,a.ch)+s+this.value.slice(b.ch)}};views.push({view:new m.MarkdownView(file,e)});return e;};
 return {app,files,texts,journals,dirs,trash,add,editor};
}
const plan=()=>({version:1,id:'move-1',sourcePath:'source.md',targetPath:'target.md',sourceBefore:'source',targetBefore:'target',sourceAfter:'source-after',targetAfter:'target-after'});
test('note writes prefer an open buffer and preserve one undoable change',async()=>{const f=appFixture(),file=f.add('source.md','disk-old'),e=f.editor(file,'unsaved');assert.equal(await m.readNote(f.app,file),'unsaved');await m.editNote(f.app,file,t=>t+'-new');assert.equal(e.value,'unsaved-new');assert.equal(f.texts.get(file.path),'disk-old');});
test('transfer writes both notes durably and removes journal',async()=>{const f=appFixture();f.add('source.md','source');f.add('target.md','target');await m.commitTransfer(f.app,plan());assert.equal(f.texts.get('source.md'),'source-after');assert.equal(f.texts.get('target.md'),'target-after');assert.equal(f.journals.size,0);});
test('transfer flushes an open editor before discarding recovery journal',async()=>{const f=appFixture(),source=f.add('source.md','source');f.add('target.md','target');const e=f.editor(source,'source');await m.commitTransfer(f.app,plan());assert.equal(e.value,'source-after');assert.equal(f.texts.get(source.path),'source-after');assert.equal(f.journals.size,0);});
test('transfer keeps concurrent source edits and the recovery journal',async()=>{const f=appFixture();f.add('source.md','source');f.add('target.md','target');f.app.afterProcess=file=>{if(file.path==='target.md')f.texts.set('source.md','user-edit')};await assert.rejects(m.commitTransfer(f.app,plan()));assert.equal(f.texts.get('source.md'),'user-edit');assert.equal(f.texts.get('target.md'),'target-after');assert.equal(f.journals.size,1);});
test('recovery is idempotent after a target-only write',async()=>{const f=appFixture();f.add('source.md','source');f.add('target.md','target-after');f.journals.set('.feishu-lite/operations/move-1.json',JSON.stringify(plan()));f.dirs.add('.feishu-lite/operations');assert.equal(await m.recoverTransfers(f.app),1);assert.equal(f.texts.get('source.md'),'source-after');assert.equal(await m.recoverTransfers(f.app),0);});
test('recovery refuses renamed or missing notes without discarding journal',async()=>{const f=appFixture();f.add('source-renamed.md','source');f.add('target.md','target-after');f.journals.set('.feishu-lite/operations/move-1.json',JSON.stringify(plan()));f.dirs.add('.feishu-lite/operations');await assert.rejects(m.recoverTransfers(f.app));assert.equal(f.texts.get('source-renamed.md'),'source');assert.equal(f.journals.size,1);});
test('malformed or escaping recovery records fail before note writes',async()=>{const f=appFixture();f.add('source.md','source');f.add('target.md','target');f.journals.set('.feishu-lite/operations/move-1.json',JSON.stringify({...plan(),sourcePath:'../source.md'}));f.dirs.add('.feishu-lite/operations');await assert.rejects(m.recoverTransfers(f.app));assert.equal(f.texts.get('source.md'),'source');assert.equal(f.texts.get('target.md'),'target');});
test('attachment cleaner treats editor project originals as owned references',async()=>{const f=appFixture();f.add('assets/original.png','binary');f.add('assets/edited.png','binary');f.add('assets/edited.png.fl-edit.json',JSON.stringify({version:1,original:'assets/original.png',width:100,height:100,crop:{x:0,y:0,width:100,height:100},shapes:[]}));f.add('note.md','![[edited.png]]');f.app.metadataCache.resolvedLinks={'note.md':{'assets/edited.png':1}};assert.deepEqual(await m.sweepUnusedAttachments({app:f.app}),[]);assert.deepEqual(f.trash,[]);});
test('a damaged project causes attachment cleanup to fail closed',async()=>{const f=appFixture();f.add('assets/original.png','binary');f.add('assets/edited.png.fl-edit.json','broken');const error=console.error;console.error=()=>{};try{assert.deepEqual(await m.sweepUnusedAttachments({app:f.app}),[]);assert.deepEqual(f.trash,[]);}finally{console.error=error;}});
